apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontext-controller-manager
  namespace: kontext-system
spec:
  template:
    metadata:
      annotations:
        kontext.dev/distribution: release
