apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: controller-manager-webhook
  namespace: kontext-system
  labels:
    app.kubernetes.io/name: kontext
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 9443
        - protocol: TCP
          port: 8081
